/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnvironmentSensorEnterprise.AirPollutionManagement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EnvironmentSensorOrganization;
import Business.Organization.GovernmentOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Sensors.AirPollutionSensor;
import Business.Sensors.Sensor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AirPollutionSolutionWorkRequest;
import Business.WorkQueue.GovernmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.time.Hour;
import org.jfree.data.time.Millisecond;
import org.jfree.data.time.Minute;
import org.jfree.data.time.Second;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

/**
 *
 * @author Akshay
 */
public class ViewAirPollutionWorkQueueJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    private EcoSystem business;
    /**
     * Creates new form ViewWorkQueueJPanel
     */
    public ViewAirPollutionWorkQueueJPanel(JPanel userProcessContainer, UserAccount userAccount, OrganizationDirectory directory, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.directory = directory;
        this.business = business;
        
        populateTable();
    }

    public void populateTable(){
        AirPollutionSolutionWorkRequest air_wrs = null;
        DefaultTableModel model = (DefaultTableModel) WorkQueuejTable.getModel();
        model.setRowCount(0);
        
        for(Organization organization : directory.getOrganizationList())
        {
            if(organization instanceof EnvironmentSensorOrganization)
            {
                for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                    if (wr instanceof AirPollutionSolutionWorkRequest){
                        air_wrs = (AirPollutionSolutionWorkRequest)wr;
            
                        Object[] row = new Object[7];
                        row[0] = air_wrs;
                        row[1] = air_wrs.getSender();
                        row[2] = air_wrs.getAirPollutionSensor().getSensorId();
                        row[3] = air_wrs.getAirPollutionSensor().getZipcode();
                        row[4] = air_wrs.getStatus();
                        row[5] = air_wrs.getMessage();
                        row[6] = air_wrs.getRequestDate();
                        model.addRow(row);
                    }
                }
                }
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        WorkQueuejTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PendingWorkQueuejTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ResolvedWorkQueuejTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SowSensorReadingButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        WorkQueuejTable.setBackground(new java.awt.Color(234, 234, 249));
        WorkQueuejTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WorkQueuejTable.setForeground(new java.awt.Color(0, 0, 51));
        WorkQueuejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request ID", "Sender", "Sensor Id", "Zipcode", "Status", "Message", "Sent Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(WorkQueuejTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Air Pollution Work Queue");

        backJButton.setBackground(new java.awt.Color(0, 0, 204));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Get Resolved Work Requests");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Get Pending Work Requests");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PendingWorkQueuejTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PendingWorkQueuejTable.setForeground(new java.awt.Color(255, 0, 51));
        PendingWorkQueuejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request ID", "Sender", "Sensor Id", "Zipcode", "Status", "Message", "Sent Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PendingWorkQueuejTable);

        ResolvedWorkQueuejTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ResolvedWorkQueuejTable.setForeground(new java.awt.Color(51, 204, 0));
        ResolvedWorkQueuejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request ID", "Sender", "Sensor Id", "Zipcode", "Status", "Message", "Sent Date", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ResolvedWorkQueuejTable);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Pending Requests");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Resolved Requests");

        SowSensorReadingButton.setBackground(new java.awt.Color(0, 0, 204));
        SowSensorReadingButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SowSensorReadingButton.setForeground(new java.awt.Color(255, 255, 255));
        SowSensorReadingButton.setText("View Sensor Reading via Line Graph");
        SowSensorReadingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SowSensorReadingButtonActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Send Resolution Message to Government");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(58, 58, 58)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1576, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1)
                                .addGap(53, 53, 53)
                                .addComponent(SowSensorReadingButton)
                                .addGap(46, 46, 46)
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(backJButton)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(SowSensorReadingButton)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AirPollutionSolutionWorkRequest air_wrs = null;
        DefaultTableModel model = (DefaultTableModel) ResolvedWorkQueuejTable.getModel();
        model.setRowCount(0);
        
        for(Organization organization : directory.getOrganizationList())
        {
            if(organization instanceof EnvironmentSensorOrganization)
            {
                for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                    if (wr instanceof AirPollutionSolutionWorkRequest)
                    {
                        air_wrs = (AirPollutionSolutionWorkRequest)wr;
            
                    if(air_wrs.getStatus().equalsIgnoreCase("Resolved"))
                    {
                        Object[] row = new Object[8];
                        row[0] = air_wrs;
                        row[1] = air_wrs.getSender();
                        row[2] = air_wrs.getAirPollutionSensor().getSensorId();
                        row[3] = air_wrs.getAirPollutionSensor().getZipcode();
                        row[4] = air_wrs.getStatus();
                        row[5] = air_wrs.getMessage();
                        row[6] = air_wrs.getRequestDate();
                        row[7] = air_wrs.getResolveDate();
                        model.addRow(row);
                    }
                    }
                }
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AirPollutionSolutionWorkRequest air_wrs = null;
        DefaultTableModel model = (DefaultTableModel) PendingWorkQueuejTable.getModel();
        model.setRowCount(0);
        
        for(Organization organization : directory.getOrganizationList())
        {
            if(organization instanceof EnvironmentSensorOrganization)
            {
                for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                    if (wr instanceof AirPollutionSolutionWorkRequest)  {
                        air_wrs = (AirPollutionSolutionWorkRequest)wr;
            
                    if(!air_wrs.getStatus().equalsIgnoreCase("Resolved"))
                    {
                        Object[] row = new Object[7];
                        row[0] = air_wrs;
                        row[1] = air_wrs.getSender();
                        row[2] = air_wrs.getAirPollutionSensor().getSensorId();
                        row[3] = air_wrs.getAirPollutionSensor().getZipcode();
                        row[4] = air_wrs.getStatus();
                        row[5] = air_wrs.getMessage();
                        row[6] = air_wrs.getRequestDate();
                        model.addRow(row);
                    }
                    }
                }
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SowSensorReadingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SowSensorReadingButtonActionPerformed
        // TODO add your handling code here:
        int row = ResolvedWorkQueuejTable.getSelectedRow();
        if(row <0){
            JOptionPane.showMessageDialog(null, "No row selected");
        }
        else
        {
            
        AirPollutionSolutionWorkRequest airPollutionSolutionWorkRequest = (AirPollutionSolutionWorkRequest) ResolvedWorkQueuejTable.getValueAt(row, 0);
        AirPollutionSensor airPollutionSensor = airPollutionSolutionWorkRequest.getAirPollutionSensor();
        
        TimeSeries s1 = new TimeSeries("Sensor Rating");
        TimeSeriesCollection dataset = new TimeSeriesCollection();
        final JFreeChart chart = ChartFactory.createTimeSeriesChart("Air Quality Index vs Date and Time",
                "Timestamp",
                "Air Quality Index", dataset,
                true,
                true,
                false);
        ChartFrame frame = new ChartFrame("XY Chart For Analysis", chart);
        frame.setVisible(true);
        frame.setSize(800, 680);
        XYPlot p = chart.getXYPlot();
        p.setRangeGridlinePaint(Color.BLACK);
        for (Map.Entry<Date, Float> entry : airPollutionSensor.getSensorValues().entrySet()) {

              s1.add(new Millisecond(entry.getKey()), entry.getValue());
        }

//Date date1 = new Date();
//s1.add(new Second(date1),98.0);
//


        dataset.addSeries(s1);
        }
    }//GEN-LAST:event_SowSensorReadingButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = ResolvedWorkQueuejTable.getSelectedRow();
        if(row <0){
            JOptionPane.showMessageDialog(null, "No row selected");
        }
        else
        {
            //AirPollutionSensor airPollutionSensor = (AirPollutionSensor)SensorReadingsjTable.getValueAt(row, 0);

//            Sensor airPollutionSenso = (Sensor)ResolvedWorkQueuejTable.getValueAt(row, 0);
            
            AirPollutionSolutionWorkRequest airPollutionSolutionWorkRequest = (AirPollutionSolutionWorkRequest)ResolvedWorkQueuejTable.getValueAt(row, 0);

            AirPollutionSensor airPollutionSensor = airPollutionSolutionWorkRequest.getAirPollutionSensor();
            GovernmentWorkRequest request = new GovernmentWorkRequest();
            request.setAirPollutionSensor(airPollutionSensor);
            request.setAirPollutionMessage("The Area bearing pincode "+airPollutionSensor.getZipcode()+"'s air quality is now better.");
            request.setSender(userAccount);
            request.setStatus("Resolution Message Sent to Government");

            Organization orgn = null;
            for(Network n: business.getNetworkList())
            {
                for(Enterprise enterprise : n.getEnterpriseDirectory().getEnterpriseList())
                {
                    for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
                    {
                        //System.out.println(org.getName());
                        if (org instanceof GovernmentOrganization){
                            orgn = org;
                            break;
                        }
                    }
                }
            }
            if (orgn!=null){

                ArrayList<Integer> sensorIDsArray = new ArrayList<Integer>();
                boolean workRequestAlreadyPresent = false;

                orgn.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Request sent to Government successfully");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PendingWorkQueuejTable;
    private javax.swing.JTable ResolvedWorkQueuejTable;
    private javax.swing.JButton SowSensorReadingButton;
    private javax.swing.JTable WorkQueuejTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
