/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnvironmentManagementRoles;

import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FloodAlertWorkRequest;
import Business.WorkQueue.GarbageManagementWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arjit
 */
public class GarbageManagementWorkqueue extends javax.swing.JPanel {
    private OrganizationDirectory organizationdirectory;
    private UserAccount userAccount;
    private JPanel userProcessContainer;
    /**
     * Creates new form GarbageManagementWorkqueue
     */
   

    GarbageManagementWorkqueue(JPanel userProcessContainer, UserAccount account, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organizationdirectory = organizationDirectory;
        populateTable();
    }
    public void populateTable(){
        GarbageManagementWorkRequest garbage_wrs = null;
        DefaultTableModel model = (DefaultTableModel) garbagetable.getModel();
        model.setRowCount(0);
        
        for(Organization organization : organizationdirectory.getOrganizationList())
        {
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof GarbageManagementWorkRequest){
                garbage_wrs = (GarbageManagementWorkRequest)wr;
            
                Object[] row = new Object[8];
                row[0] = garbage_wrs;
                row[1] = garbage_wrs.getSender();
                row[2] = garbage_wrs.getGarbagesensor().getSensorId();
                row[3] = garbage_wrs.getGarbagesensor().getZipcode();
                row[4] = garbage_wrs.getStatus();
                row[5] = garbage_wrs.getMessage();
                row[6] = garbage_wrs.getRequestDate();
                row[7] = garbage_wrs.getResolveDate();
                model.addRow(row);
        }
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        garbagetable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        garbagetable.setBackground(new java.awt.Color(234, 234, 249));
        garbagetable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        garbagetable.setForeground(new java.awt.Color(0, 0, 51));
        garbagetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request ID", "Sender", "Sensor Id", "Zipcode", "Status", "Message", "Received Date", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(garbagetable);

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 123, 1580, 177);

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Resolve");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(600, 394, 85, 25);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(40, 386, 87, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Garbage Management Work Queue");
        add(jLabel1);
        jLabel1.setBounds(113, 48, 416, 29);

        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(1090, 240, 41, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/pics/636106688819089273-DSC-1873.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-820, -760, 2720, 1900);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = garbagetable.getSelectedRow();
        if(row <0){
            JOptionPane.showMessageDialog(null, "No row selected");
        }else{
        Random rn = new Random();

        WorkRequest workRequest = (WorkRequest) garbagetable.getValueAt(row, 0);

        GarbageManagementWorkRequest garbageWorkRequest = (GarbageManagementWorkRequest)workRequest;
        garbageWorkRequest.setStatus("Resolved");
        garbageWorkRequest.setResolveDate(new Date());

        garbageWorkRequest.getGarbagesensor().setCurrentlevel(0);

        populateTable();
        JOptionPane.showMessageDialog(null, "Resolved");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable garbagetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
